### ISSUE TITLE
Issue to create .geo in the tutorial

### ISSUE THREAD

**Issue by Krys1202** [jonathanlambrechts/qgis-gmsh#13]
Hi!
Thank you for a great plugin and tutorial. I'm new with all these tools and your videos are very helpful!
I have been trying to use the QGIS gmsh plugin by following the tutorial with your files. For me I followed all your steps but when I am at the step to generate the .geo file I have a message error:

An error has occurred while executing Python code: 

TypeError: LineString geometry cannot be converted to a multilinestring. Only multi linestring or curves are permitted. 
Traceback (most recent call last):
  File "/home/christelle/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gmsh/exportGeometry.py", line 298, in saveGeo
    status = exportGeo(filename, activeLayers, insideLayers, meshSizeLayer, crs, forceAllBnd)
  File "/home/christelle/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gmsh/exportGeometry.py", line 214, in exportGeo
    addLayer(l, progress, False)
  File "/home/christelle/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gmsh/exportGeometry.py", line 203, in addLayer
    lines = geom.asMultiPolyline()
TypeError: LineString geometry cannot be converted to a multilinestring. Only multi linestring or curves are permitted.

Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python Path:
/usr/share/qgis/python
/home/christelle/.local/share/QGIS/QGIS3/profiles/default/python
/home/christelle/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/christelle/.local/share/QGIS/QGIS3/profiles/default/python

Could you help me and tell me what I am doing wrong please?
Thanks a lot

Kind regards,
Christelle

**Comment by Krys1202** [comment]
I tried to create a .geo file with my own data and I see the file created .txt but without the extension .geo thus it's not recognized for the creation of the mesh. See screenshot attached...
What's wrong with this file? Is there a limit of number of points ( huge file)?

![Screenshot from 2021-02-18 15-56-23](https://user-images.githubusercontent.com/36248064/108307457-e526ef80-7201-11eb-830c-cb2e047062d5.png)

**Comment by Krys1202** [comment]
and I put here the end of the file that should be a .geo but is .txt ....
....
....
Point(IP+3651) = {149.7026245493245, -44.16857696742709, 0};
Spline(IL+99) = {IP+3648, IP+3650, IP+3651, IP+3649};
NF = newf;
Field[NF] = Structured;
Field[NF].TextFormat = 0;
Field[NF].FileName = "/home/christelle/Model/Input/tasinputgeo.dat";
Background Field = NF;
Plane Surface(IS) = {ILL:ILL+91};
Physical Surface("Domain") = {IS};
Physical Line("coast") = {IL + 11,IL + 12,IL + 81,IL + 85,IL + 90,IL + 91,IL + 92,IL + 93,IL + 96,IL + 97,IL + 98};

**Comment by jonathanlambrechts** [comment]
Hi,
1) I do not actively develop this plugin anymore. If you are confident with python, I encourage you to use this library instead that provides similar functionalities : https://pypi.org/project/seamsh/ .
2) I do not understand what append with your file and why it ended up with a ".txt" extension but the content looks ok, so you can just rename it to '.geo' and open it in gmsh.
3) For the Linestring to multilinestring conversion problem, can you send me a small example that fails ? I'll try to fix the plugin.

**Comment by Krys1202** [comment]
Hello,
1-Thanks for the link to seamsh. I'm going to try!
2-Yes I was able to open it in gmsh it's just weird it doesn't create the .geo file...
And in gmsh i have this error message ( cf png attached)
![Screenshot from 2021-02-22 15-49-02](https://user-images.githubusercontent.com/36248064/108663887-ac4e8980-7525-11eb-8996-77ffd1852aae.png)
Do you know what I did wrong?
3- I used the files from the tutorials, what files/small example do you want?

Kind regards,
Christelle
